name: github actions
on: 
    schedule:
        - cron: "0 18 * * *"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: set up python3.8
              uses: actions/setup-python@v4
              with: python-version: '3.8'
            
            - name: install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: run script
              run: python src/main.py

            - name: push to main
              run: |
                git config --global user.name "wyaming89"
                git config --global user.email "wyaming89@gmail.com"

                git add -A
                git commit -m "update"
                git push -u origin main